### ISSUE TITLE
Receiving an error when cron job runs Parse error Invalid numeric literal

### ISSUE THREAD

**Issue by FDrebin** [dak180/FreeNAS-Report#37]
Receiving the error : parse error: Invalid numeric literal at line 1, column 9

Basic script and config with only the email address filled in, followed the steps to install the "bc" package required. Running TrueNAS Scale ElectricEel-24.10.0.2

**Comment by FDrebin** [comment]
Interestingly, the individual drives have SMART status, but the report doesnt include any of them. They are also regular SATA drives, not SAS so i do not have that enabled.

![image](https://github.com/user-attachments/assets/2fae323b-9088-4415-85e6-318082dd154a)

**Comment by dak180** [comment]
Please run the script with the `-d` option and attach the archive here.

**Comment by FDrebin** [comment]
Thank you for the reply, please see attached.  I did need to extract and re-zip it for Github not to complain.
[dumpfiles.zip](https://github.com/user-attachments/files/17788546/dumpfiles.zip)

**Comment by dak180** [comment]
So there are two problems I see here (and unfortunately there is little I can do about them), the first being that you are using [SMR drives](https://www.truenas.com/community/resources/list-of-known-smr-drives.141/)  this is likely to result in data loss sooner rather than later, the second issue (and why the script is not showing the drives) is that they appear to cause an error with `smartctl` when attempting to output in json which the script requires.

For the first I recommend getting a good backup of everything currently on the pool that you care about and then replace all of the SMR drives and recreate the pool from scratch.

For the second I recommend filing a bug report with [smartmontools](https://www.smartmontools.org); you can see the below error message in any of the json files you sent me:
```
Smartctl: Exception: json.cpp(401): Assertion failed: value != nullptr
Please inform smartmontools-support@listi.jpberlin.de, including output of smartctl -V.
```
